name: Radium workflow

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pipx install poetry==1.2.0
      - name: run install
        run: make install
      - name: run linter
        run: make lint
